baseURL = "https://www.vigilant-kilby-8072bf.netlify.com"
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "A port of the Grayscale theme to Hugo"
    author = "RunningStream"
